# Generated by Django 5.2.5 on 2025-08-10 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card_varities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='card/')),
                ('date_addded', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('MC', 'Marage Card'), ('RC', 'Reception Card'), ('DC', 'Death Card'), ('BC', 'Birthday Card'), ('BS', 'Baby Shower Card')], max_length=2)),
                ('description', models.TextField(verbose_name='')),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
