# Generated by Django 5.2.5 on 2025-08-10 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=15)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('location', models.CharField(max_length=120)),
                ('skin', models.CharField(choices=[('D', 'Dark'), ('P', 'Pale'), ('B', 'Brownish')], max_length=50)),
                ('Marriage_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=2)),
                ('profession', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
