# Generated by Django 5.2.5 on 2025-08-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='bloodgroup',
            field=models.CharField(choices=[('O+', 'O positive'), ('O-', 'O negative'), ('A+', 'A positive'), ('A-', 'A negative'), ('B+', 'B positive'), ('B-', 'B negative'), ('AB+', 'AB positive'), ('AB-', 'AB negative')], default=''),
        ),
    ]
