# Generated by Django 5.2.5 on 2025-08-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('YA', 'Young Adult'), ('DT', 'Documentary'), ('FI', 'Fiction'), ('RO', 'Romance'), ('FA', 'Fantacy'), ('KI', 'Kids')])),
                ('Published_yr', models.DateTimeField()),
                ('About_book', models.TextField()),
            ],
        ),
    ]
