# Generated by Django 5.2.5 on 2025-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Published_yr',
            field=models.DateField(),
        ),
    ]
